#Plots the same data generated by the Haskell program
import matplotlib.pyplot as pl
import numpy as np


def main():
    energies = np.loadtxt("log_avg_ste.dat")
    magnitudes = np.loadtxt("log_avg_stm.dat")
    zcrs = np.loadtxt("avg_zcr.dat")

    pl.scatter(energies, magnitudes, color = "red")
    pl.title("Energy against Magnitude")
    pl.xlabel("Log average of energy")
    pl.ylabel("Log average of magnitudes")
    pl.savefig("eam.png", bbox_inches='tight')
    
    pl.scatter(energies, zcrs, color = "red")
    pl.title("Energy against Zero Crossing Rate")
    pl.xlabel("Log of Average of Energy")
    pl.ylabel("Average Zero Crossing Rate")
    pl.savefig("eac.png", bbox_inches='tight')


    pl.scatter(magnitudes, zcrs, color = "red")
    pl.title("Magnitude against Zero Crossing Rate")
    pl.xlabel("Log of average of Magnitudes")
    pl.ylabel("Average of Zero Crossing Rates")
    pl.savefig("maz.png", bbox_inches='tight')

main()
